---
namespace: train
state:
  strength: 0

---
Start:
  - [clearScreen: {}]
  - You walk into another room, where you find a monster!
  - What would you like to do?
  - choices:
      fight: Fight
      train: Train
      ...: Timeout

Fight:
  - You fight and fight and fight...
  - if strength > 2:
      - And you finally defeat the monster!
      - Congrats!
      - goto: End
    else:
      - But you weren't strong enough!
      - Should you try again?
      - choices:
          try again: Fight
          train: Train
          ...: Timeout

Train:
  - if strength < 3:
      - |
        *training noises*
      - set:
          strength +: 1
      - You trained and got stronger. You now have a strength score of ${strength}.
    else:
      - You've already trained too much!
  - What would you like to do now?
  - choices:
      train: Train
      fight: Fight
      ...: Timeout

Timeout:
  - You took to long to decide! Looks like you need some training...
  - goto: Train
